import { CateringProduct } from './types';

// Helper to create pan pricing with custom serving sizes per item
function panPricing(
  halfPrice: number,
  fullPrice: number,
  halfServesMin: number,
  halfServesMax: number,
  fullServesMin: number,
  fullServesMax: number,
) {
  return {
    type: 'pan' as const,
    sizes: [
      { size: 'half' as const, price: halfPrice, servesMin: halfServesMin, servesMax: halfServesMax },
      { size: 'full' as const, price: fullPrice, servesMin: fullServesMin, servesMax: fullServesMax },
    ],
  };
}

export const CATERING_PRODUCTS: CateringProduct[] = [
  {
    id: 'mini-tacos',
    title: 'Mini Tacos',
    description: 'Choice of beef, chicken, or cheese. Bite-sized tacos perfect for any gathering.',
    image: '/images/menu/mini-tacos.jpg',
    categories: ['appetizers'],
    pricing: panPricing(30, 60, 24, 24, 48, 48),
    tags: ['appetizer', 'popular', 'mexican'],
    menuEngineering: {
      classification: 'PUZZLE',
      foodCost: 22,
      salesRank: 7,
      placementPriority: 1,
      visualWeight: 'high',
      descriptionStrategy: 'enhance',
      badgeText: 'Crowd Favorite',
      enhancedDescription: 'Pepe\'s famous bite-sized tacos — the #1 party starter since 1967. Choose beef, chicken, or cheese for a crowd-pleaser that disappears fast.',
      salesVelocity7d: null,
      salesVelocity30d: null,
      trendDirection: null,
      lastClassifiedAt: null,
    },
    variants: {
      label: 'Filling',
      options: [
        { id: 'beef', label: 'Beef' },
        { id: 'chicken', label: 'Chicken' },
        { id: 'cheese', label: 'Cheese' },
      ],
      selectionMode: 'single',
    },
  },
  {
    id: 'mini-flautas',
    title: 'Mini Flautas',
    description: 'Choice of beef or chicken. Crispy rolled tortillas filled with seasoned meat.',
    image: '/images/menu/mini-flautas.jpg',
    categories: ['appetizers'],
    pricing: panPricing(39, 66, 24, 24, 48, 48),
    tags: ['appetizer', 'mexican'],
    menuEngineering: {
      classification: 'PUZZLE',
      foodCost: 20,
      salesRank: 22,
      placementPriority: 8,
      visualWeight: 'medium',
      descriptionStrategy: 'enhance',
      badgeText: 'Hidden Gem',
      enhancedDescription: 'Crispy rolled tortillas filled with seasoned beef or chicken — a crunchy, satisfying appetizer your guests won\'t stop reaching for.',
      salesVelocity7d: null,
      salesVelocity30d: null,
      trendDirection: null,
      lastClassifiedAt: null,
    },
    variants: {
      label: 'Filling',
      options: [
        { id: 'beef', label: 'Beef' },
        { id: 'chicken', label: 'Chicken' },
      ],
      selectionMode: 'single',
    },
  },
  {
    id: 'jalapeno-poppers',
    title: 'Jalapeño Poppers',
    description: 'Choice of cheddar or cream cheese. Stuffed jalapeños with a crispy coating.',
    image: '/images/menu/jalapeno-poppers.jpg',
    categories: ['appetizers'],
    pricing: panPricing(41, 69, 24, 24, 48, 48),
    tags: ['appetizer', 'spicy', 'mexican'],
    menuEngineering: {
      classification: 'PUZZLE',
      foodCost: 17,
      salesRank: 23,
      placementPriority: 9,
      visualWeight: 'medium',
      descriptionStrategy: 'enhance',
      badgeText: 'Try Something New',
      enhancedDescription: 'Crispy-coated stuffed jalapeños with your choice of cheddar or cream cheese — the perfect spicy-creamy appetizer combo.',
      salesVelocity7d: null,
      salesVelocity30d: null,
      trendDirection: null,
      lastClassifiedAt: null,
    },
    variants: {
      label: 'Filling',
      options: [
        { id: 'cheddar', label: 'Cheddar' },
        { id: 'cream-cheese', label: 'Cream Cheese' },
      ],
      selectionMode: 'single',
    },
  },
  {
    id: 'mexican-buffalo-wings',
    title: 'Mexican Buffalo Wings',
    description: 'Choice of blue cheese or ranch dipping sauce. Wings with a Mexican-inspired buffalo kick.',
    image: '/images/menu/mexican-buffalo-wings.jpg',
    categories: ['appetizers'],
    pricing: panPricing(45, 90, 24, 24, 48, 48),
    tags: ['appetizer', 'spicy', 'popular', 'mexican'],
    menuEngineering: {
      classification: 'PLOWHORSE',
      foodCost: 34,
      salesRank: 12,
      placementPriority: 5,
      visualWeight: 'medium',
      descriptionStrategy: 'maintain',
      badgeText: null,
      enhancedDescription: null,
      salesVelocity7d: null,
      salesVelocity30d: null,
      trendDirection: null,
      lastClassifiedAt: null,
    },
    variants: {
      label: 'Dipping Sauce',
      options: [
        { id: 'blue-cheese', label: 'Blue Cheese' },
        { id: 'ranch', label: 'Ranch' },
      ],
      selectionMode: 'single',
    },
  },
  {
    id: 'taco-salad',
    title: 'Taco Salad',
    description: 'Lettuce, shredded carrots, tomatoes, and green peppers. Choice of beef, chicken, or cheese served on the side.',
    image: '/images/menu/taco-salad.jpg',
    categories: ['appetizers'],
    pricing: panPricing(39, 60, 10, 15, 20, 30),
    tags: ['appetizer', 'salad', 'healthy', 'mexican'],
    menuEngineering: {
      classification: 'PUZZLE',
      foodCost: 17,
      salesRank: 25,
      placementPriority: 10,
      visualWeight: 'low',
      descriptionStrategy: 'enhance',
      badgeText: 'House Favorite',
      enhancedDescription: 'A fresh, colorful spread of lettuce, shredded carrots, tomatoes, and green peppers with your choice of protein served on the side.',
      salesVelocity7d: null,
      salesVelocity30d: null,
      trendDirection: null,
      lastClassifiedAt: null,
    },
    variants: {
      label: 'Filling',
      options: [
        { id: 'beef', label: 'Beef' },
        { id: 'chicken', label: 'Chicken' },
        { id: 'cheese', label: 'Cheese' },
      ],
      selectionMode: 'single',
    },
  },
  {
    id: 'chips-medium',
    title: 'Chips - Medium Bag',
    description: 'Fresh tortilla chips, medium bag. Perfect for dipping with salsa or guacamole.',
    image: '/images/menu/chips-medium.jpg',
    categories: ['appetizers'],
    pricing: { type: 'per-each' as const, priceEach: 5.25 },
    tags: ['appetizer', 'chips', 'mexican'],
    menuEngineering: {
      classification: 'DOG',
      foodCost: 10,
      salesRank: 30,
      placementPriority: 30,
      visualWeight: 'low',
      descriptionStrategy: 'minimize',
      badgeText: null,
      enhancedDescription: null,
      salesVelocity7d: null,
      salesVelocity30d: null,
      trendDirection: null,
      lastClassifiedAt: null,
    },
  },
  {
    id: 'chips-large',
    title: 'Chips - Large Bag',
    description: 'Fresh tortilla chips, large bag. Great for medium-sized parties.',
    image: '/images/menu/chips.jpg',
    categories: ['appetizers'],
    pricing: { type: 'per-each' as const, priceEach: 7.25 },
    tags: ['appetizer', 'chips', 'mexican'],
    menuEngineering: {
      classification: 'PLOWHORSE',
      foodCost: 10,
      salesRank: 17,
      placementPriority: 15,
      visualWeight: 'low',
      descriptionStrategy: 'maintain',
      badgeText: null,
      enhancedDescription: null,
      salesVelocity7d: null,
      salesVelocity30d: null,
      trendDirection: null,
      lastClassifiedAt: null,
    },
  },
  {
    id: 'chips-xlarge',
    title: 'Chips - X-Large Bag',
    description: 'Fresh tortilla chips, extra-large bag. Ideal for large events and gatherings.',
    image: '/images/menu/chips-xlarge.jpg',
    categories: ['appetizers'],
    pricing: { type: 'per-each' as const, priceEach: 15.25 },
    tags: ['appetizer', 'chips', 'mexican'],
    menuEngineering: {
      classification: 'PUZZLE',
      foodCost: 10,
      salesRank: 29,
      placementPriority: 11,
      visualWeight: 'medium',
      descriptionStrategy: 'enhance',
      badgeText: 'Best Value',
      enhancedDescription: 'Fresh tortilla chips for the whole party — our extra-large bag is the best value for events of 20+ guests.',
      salesVelocity7d: null,
      salesVelocity30d: null,
      trendDirection: null,
      lastClassifiedAt: null,
    },
  },
  {
    id: 'beef-taco-filling',
    title: 'Beef Taco Filling',
    description: 'Seasoned beef taco filling. Half pan makes about 30-35 tacos, full pan about 60-70 tacos. Includes 3 warm tortillas per taco.',
    image: '/images/menu/beef-taco-filling.jpg',
    categories: ['entrees'],
    pricing: panPricing(75, 140, 30, 35, 60, 70),
    tags: ['entree', 'beef', 'taco', 'taco-filling', 'popular', 'mexican'],
    menuEngineering: {
      classification: 'STAR',
      foodCost: 30,
      salesRank: 4,
      placementPriority: 2,
      visualWeight: 'high',
      descriptionStrategy: 'enhance',
      badgeText: 'Crowd Favorite',
      enhancedDescription: 'Pepe\'s classic seasoned beef taco filling — a crowd favorite that makes 30-70 tacos per pan. Includes warm tortillas for the ultimate taco bar.',
      salesVelocity7d: null,
      salesVelocity30d: null,
      trendDirection: null,
      lastClassifiedAt: null,
    },
  },
  {
    id: 'chicken-taco-filling',
    title: 'Chicken Taco Filling',
    description: 'Seasoned chicken taco filling. Half pan makes about 30-35 tacos, full pan about 60-70 tacos. Includes 3 warm tortillas per taco.',
    image: '/images/menu/chicken-taco-filling.jpg',
    categories: ['entrees'],
    pricing: panPricing(85, 140, 30, 35, 60, 70),
    tags: ['entree', 'chicken', 'taco', 'taco-filling', 'popular', 'mexican'],
    menuEngineering: {
      classification: 'STAR',
      foodCost: 24,
      salesRank: 2,
      placementPriority: 2,
      visualWeight: 'high',
      descriptionStrategy: 'enhance',
      badgeText: 'Most Popular you must try this!!',
      enhancedDescription: 'Our most-ordered taco filling — seasoned chicken that makes 30-70 tacos per pan. Includes warm tortillas for the ultimate taco bar.',
      salesVelocity7d: null,
      salesVelocity30d: null,
      trendDirection: null,
      lastClassifiedAt: null,
    },
  },
  {
    id: 'pork-taco-filling',
    title: 'Pork Taco Filling',
    description: 'Seasoned pork taco filling. Half pan makes about 30-35 tacos, full pan about 60-70 tacos. Includes 3 warm tortillas per taco.',
    image: '/images/menu/pork-taco-filling.jpg',
    categories: ['entrees'],
    pricing: panPricing(75, 140, 30, 35, 60, 70),
    tags: ['entree', 'pork', 'taco', 'taco-filling', 'mexican'],
    menuEngineering: {
      classification: 'PUZZLE',
      foodCost: 26,
      salesRank: 26,
      placementPriority: 12,
      visualWeight: 'high',
      descriptionStrategy: 'enhance',
      badgeText: 'Try Something New',
      enhancedDescription: 'Slow-seasoned pork taco filling for an authentic twist on your taco bar. Makes 30-70 tacos per pan with warm tortillas included.',
      salesVelocity7d: null,
      salesVelocity30d: null,
      trendDirection: null,
      lastClassifiedAt: null,
    },
  },
  {
    id: 'chicken-fajitas',
    title: 'Chicken Fajitas',
    description: 'Grilled chicken fajitas with sautéed peppers and onions. Half pan includes 30 tortillas plus 16oz sour cream, pico de gallo, and guacamole. Full pan includes 60 tortillas plus 32oz each. Choice of corn or flour tortillas.',
    image: '/images/menu/chicken-fajitas.jpg',
    categories: ['entrees'],
    pricing: panPricing(85, 125, 10, 15, 20, 30),
    tags: ['entree', 'chicken', 'fajita', 'popular', 'mexican'],
    menuEngineering: {
      classification: 'STAR',
      foodCost: 27,
      salesRank: 1,
      placementPriority: 1,
      visualWeight: 'high',
      descriptionStrategy: 'enhance',
      badgeText: 'Chef\'s Pick',
      enhancedDescription: 'Pepe\'s signature sizzling chicken fajitas — our most-loved entree since 1967. Served with sautéed peppers, onions, tortillas, sour cream, pico, and guacamole.',
      salesVelocity7d: null,
      salesVelocity30d: null,
      trendDirection: null,
      lastClassifiedAt: null,
    },
    variants: {
      label: 'Tortilla',
      options: [
        { id: 'corn', label: 'Corn' },
        { id: 'flour', label: 'Flour' },
      ],
      selectionMode: 'single',
    },
  },
  {
    id: 'steak-fajitas',
    title: 'Steak Fajitas',
    description: 'Grilled steak fajitas with sautéed peppers and onions. Half pan includes 30 tortillas plus 16oz sour cream, pico de gallo, and guacamole. Full pan includes 60 tortillas plus 32oz each. Choice of corn or flour tortillas.',
    image: '/images/menu/steak-fajitas.jpg',
    categories: ['entrees'],
    pricing: panPricing(85, 125, 10, 15, 20, 30),
    tags: ['entree', 'beef', 'fajita', 'premium', 'mexican'],
    menuEngineering: {
      classification: 'PUZZLE',
      foodCost: 33,
      salesRank: 10,
      placementPriority: 6,
      visualWeight: 'high',
      descriptionStrategy: 'maintain',
      badgeText: null,
      enhancedDescription: null,
      salesVelocity7d: null,
      salesVelocity30d: null,
      trendDirection: null,
      lastClassifiedAt: null,
    },
    variants: {
      label: 'Tortilla',
      options: [
        { id: 'corn', label: 'Corn' },
        { id: 'flour', label: 'Flour' },
      ],
      selectionMode: 'single',
    },
  },
  {
    id: 'combo-fajitas',
    title: 'Combo Fajitas',
    description: 'A combination of grilled chicken and steak fajitas with sautéed peppers and onions. Half pan includes 30 tortillas plus 16oz sour cream, pico de gallo, and guacamole. Full pan includes 60 tortillas plus 32oz each. Choice of corn or flour tortillas.',
    image: '/images/menu/combo-fajitas.jpg',
    categories: ['entrees'],
    pricing: panPricing(85, 125, 10, 15, 20, 30),
    tags: ['entree', 'combo', 'fajita', 'popular', 'mexican'],
    menuEngineering: {
      classification: 'STAR',
      foodCost: 30,
      salesRank: 3,
      placementPriority: 3,
      visualWeight: 'high',
      descriptionStrategy: 'enhance',
      badgeText: 'Crowd Favorite',
      enhancedDescription: 'The best of both worlds — grilled chicken AND steak fajitas together. Our most popular choice for events that want to impress everyone.',
      salesVelocity7d: null,
      salesVelocity30d: null,
      trendDirection: null,
      lastClassifiedAt: null,
    },
    variants: {
      label: 'Tortilla',
      options: [
        { id: 'corn', label: 'Corn' },
        { id: 'flour', label: 'Flour' },
      ],
      selectionMode: 'single',
    },
  },
  {
    id: 'vegetable-fajitas',
    title: 'Vegetable Fajitas',
    description: 'Grilled vegetable fajitas with sautéed peppers and onions. Half pan includes 30 tortillas plus 16oz sour cream, pico de gallo, and guacamole. Full pan includes 60 tortillas plus 32oz each. Choice of corn or flour tortillas.',
    image: '/images/menu/vegetable-fajitas.jpg',
    categories: ['entrees'],
    pricing: panPricing(85, 125, 10, 15, 20, 30),
    tags: ['entree', 'vegetarian', 'fajita', 'mexican'],
    menuEngineering: {
      classification: 'PUZZLE',
      foodCost: 20,
      salesRank: 27,
      placementPriority: 13,
      visualWeight: 'medium',
      descriptionStrategy: 'enhance',
      badgeText: 'House Favorite',
      enhancedDescription: 'A colorful medley of grilled vegetables with sautéed peppers and onions — our most-requested vegetarian option with the same great fajita experience.',
      salesVelocity7d: null,
      salesVelocity30d: null,
      trendDirection: null,
      lastClassifiedAt: null,
    },
    variants: {
      label: 'Tortilla',
      options: [
        { id: 'corn', label: 'Corn' },
        { id: 'flour', label: 'Flour' },
      ],
      selectionMode: 'single',
    },
  },
  {
    id: 'carnitas-regular',
    title: 'Carnitas Regular',
    description: 'Slow-cooked, tender pork carnitas. Includes 2 dozen tortillas per half pan.',
    image: '/images/menu/carnitas-regular.jpg',
    categories: ['entrees'],
    pricing: panPricing(70, 140, 8, 12, 18, 25),
    tags: ['entree', 'pork', 'carnitas', 'popular', 'mexican'],
    menuEngineering: {
      classification: 'STAR',
      foodCost: 28,
      salesRank: 6,
      placementPriority: 4,
      visualWeight: 'high',
      descriptionStrategy: 'enhance',
      badgeText: 'Chef\'s Pick',
      enhancedDescription: 'Pepe\'s famous slow-cooked carnitas — fork-tender pork braised for hours in our authentic recipe. A crowd favorite since 1967.',
      salesVelocity7d: null,
      salesVelocity30d: null,
      trendDirection: null,
      lastClassifiedAt: null,
    },
  },
  {
    id: 'carnitas-mild-salsa',
    title: 'Carnitas with Mild Salsa',
    description: 'Slow-cooked, tender pork carnitas topped with mild salsa. Includes 2 dozen tortillas per half pan.',
    image: '/images/menu/carnitas-mild.jpg',
    categories: ['entrees'],
    pricing: panPricing(70, 110, 8, 12, 18, 25),
    tags: ['entree', 'pork', 'carnitas', 'mexican'],
    menuEngineering: {
      classification: 'DOG',
      foodCost: 29,
      salesRank: 31,
      placementPriority: 28,
      visualWeight: 'low',
      descriptionStrategy: 'minimize',
      badgeText: null,
      enhancedDescription: null,
      salesVelocity7d: null,
      salesVelocity30d: null,
      trendDirection: null,
      lastClassifiedAt: null,
    },
  },
  {
    id: 'carnitas-hot-green-salsa',
    title: 'Carnitas with Hot Green Salsa',
    description: 'Slow-cooked, tender pork carnitas topped with hot green salsa. Includes 2 dozen tortillas per half pan.',
    image: '/images/menu/carnitas-hot.jpg',
    categories: ['entrees'],
    pricing: panPricing(70, 110, 8, 12, 18, 25),
    tags: ['entree', 'pork', 'carnitas', 'spicy', 'mexican'],
    menuEngineering: {
      classification: 'DOG',
      foodCost: 29,
      salesRank: 32,
      placementPriority: 29,
      visualWeight: 'low',
      descriptionStrategy: 'minimize',
      badgeText: null,
      enhancedDescription: null,
      salesVelocity7d: null,
      salesVelocity30d: null,
      trendDirection: null,
      lastClassifiedAt: null,
    },
  },
  {
    id: 'tamales',
    title: 'Tamales',
    description: 'Choice of chicken or pork. Traditional Mexican tamales wrapped in corn husks. 20 pieces per half pan.',
    image: '/images/menu/tamales.jpg',
    categories: ['entrees'],
    pricing: panPricing(35, 70, 10, 15, 20, 30),
    tags: ['entree', 'tamale', 'traditional', 'mexican'],
    menuEngineering: {
      classification: 'PUZZLE',
      foodCost: 22,
      salesRank: 24,
      placementPriority: 14,
      visualWeight: 'medium',
      descriptionStrategy: 'enhance',
      badgeText: 'Hidden Gem',
      enhancedDescription: 'Authentic handmade tamales wrapped in corn husks — a traditional Mexican favorite your guests will love. 20 pieces per half pan.',
      salesVelocity7d: null,
      salesVelocity30d: null,
      trendDirection: null,
      lastClassifiedAt: null,
    },
    variants: {
      label: 'Filling',
      options: [
        { id: 'chicken', label: 'Chicken' },
        { id: 'pork', label: 'Pork' },
      ],
      selectionMode: 'single',
    },
  },
  {
    id: 'enchiladas',
    title: 'Enchiladas',
    description: 'Traditional enchiladas with choice of filling and sauce. 20 pieces per half pan.',
    image: '/images/menu/enchiladas.jpg',
    categories: ['entrees'],
    pricing: panPricing(40, 70, 10, 15, 20, 30),
    tags: ['entree', 'enchilada', 'popular', 'mexican'],
    menuEngineering: {
      classification: 'PUZZLE',
      foodCost: 24,
      salesRank: 16,
      placementPriority: 15,
      visualWeight: 'medium',
      descriptionStrategy: 'enhance',
      badgeText: 'House Favorite',
      enhancedDescription: 'Classic enchiladas smothered in sauce and cheese — a comforting Mexican staple perfect alongside fajitas or as a main course. 20 pieces per half pan.',
      salesVelocity7d: null,
      salesVelocity30d: null,
      trendDirection: null,
      lastClassifiedAt: null,
    },
  },
  {
    id: 'taco-tray-25',
    title: 'Taco Tray - 25 Tacos',
    description: 'Tray of 25 tacos with choice of beef, chicken, or pork filling. Ready to serve.',
    image: '/images/menu/taco-tray-25.jpg',
    categories: ['entrees'],
    pricing: { type: 'per-each' as const, priceEach: 75 },
    tags: ['entree', 'taco', 'taco-tray', 'mexican'],
    menuEngineering: {
      classification: 'PLOWHORSE',
      foodCost: 27,
      salesRank: 18,
      placementPriority: 16,
      visualWeight: 'medium',
      descriptionStrategy: 'maintain',
      badgeText: null,
      enhancedDescription: null,
      salesVelocity7d: null,
      salesVelocity30d: null,
      trendDirection: null,
      lastClassifiedAt: null,
    },
    variants: {
      label: 'Filling',
      options: [
        { id: 'beef', label: 'Beef' },
        { id: 'chicken', label: 'Chicken' },
        { id: 'pork', label: 'Pork' },
      ],
      selectionMode: 'split',
      splitTotal: 25,
    },
  },
  {
    id: 'taco-tray-50',
    title: 'Taco Tray - 50 Tacos',
    description: 'Tray of 50 tacos with choice of beef, chicken, or pork filling. Ready to serve.',
    image: '/images/menu/taco-tray-50.jpg',
    categories: ['entrees'],
    pricing: { type: 'per-each' as const, priceEach: 140 },
    tags: ['entree', 'taco', 'taco-tray', 'popular', 'mexican'],
    menuEngineering: {
      classification: 'STAR',
      foodCost: 26,
      salesRank: 5,
      placementPriority: 5,
      visualWeight: 'high',
      descriptionStrategy: 'enhance',
      badgeText: 'Most Popular',
      enhancedDescription: 'Our most-ordered taco tray — 50 ready-to-serve tacos with your choice of beef, chicken, or pork. Split the filling any way you like.',
      salesVelocity7d: null,
      salesVelocity30d: null,
      trendDirection: null,
      lastClassifiedAt: null,
    },
    variants: {
      label: 'Filling',
      options: [
        { id: 'beef', label: 'Beef' },
        { id: 'chicken', label: 'Chicken' },
        { id: 'pork', label: 'Pork' },
      ],
      selectionMode: 'split',
      splitTotal: 50,
    },
  },
  {
    id: 'taco-tray-75',
    title: 'Taco Tray - 75 Tacos',
    description: 'Tray of 75 tacos with choice of beef, chicken, or pork filling. Ready to serve.',
    image: '/images/menu/taco-tray-75.jpg',
    categories: ['entrees'],
    pricing: { type: 'per-each' as const, priceEach: 200 },
    tags: ['entree', 'taco', 'taco-tray', 'mexican'],
    menuEngineering: {
      classification: 'DOG',
      foodCost: 27,
      salesRank: 33,
      placementPriority: 31,
      visualWeight: 'low',
      descriptionStrategy: 'minimize',
      badgeText: null,
      enhancedDescription: null,
      salesVelocity7d: null,
      salesVelocity30d: null,
      trendDirection: null,
      lastClassifiedAt: null,
    },
    variants: {
      label: 'Filling',
      options: [
        { id: 'beef', label: 'Beef' },
        { id: 'chicken', label: 'Chicken' },
        { id: 'pork', label: 'Pork' },
      ],
      selectionMode: 'split',
      splitTotal: 75,
    },
  },
  {
    id: 'taco-tray-100',
    title: 'Taco Tray - 100 Tacos',
    description: 'Tray of 100 tacos with choice of beef, chicken, or pork filling. Ready to serve. Best value for large events.',
    image: '/images/menu/taco-tray-100.jpg',
    categories: ['entrees'],
    pricing: { type: 'per-each' as const, priceEach: 250 },
    tags: ['entree', 'taco', 'taco-tray', 'popular', 'mexican'],
    menuEngineering: {
      classification: 'PLOWHORSE',
      foodCost: 28,
      salesRank: 11,
      placementPriority: 7,
      visualWeight: 'medium',
      descriptionStrategy: 'maintain',
      badgeText: null,
      enhancedDescription: null,
      salesVelocity7d: null,
      salesVelocity30d: null,
      trendDirection: null,
      lastClassifiedAt: null,
    },
    variants: {
      label: 'Filling',
      options: [
        { id: 'beef', label: 'Beef' },
        { id: 'chicken', label: 'Chicken' },
        { id: 'pork', label: 'Pork' },
      ],
      selectionMode: 'split',
      splitTotal: 100,
    },
  },
  {
    id: 'spanish-rice',
    title: 'Spanish Rice',
    description: 'Traditional Spanish rice seasoned with tomatoes, onions, and spices.',
    image: '/images/menu/spanish-rice.jpg',
    categories: ['sides'],
    pricing: panPricing(30, 50, 15, 20, 30, 35),
    tags: ['side', 'rice', 'popular', 'vegetarian', 'mexican'],
    menuEngineering: {
      classification: 'PLOWHORSE',
      foodCost: 12,
      salesRank: 8,
      placementPriority: 8,
      visualWeight: 'medium',
      descriptionStrategy: 'maintain',
      badgeText: null,
      enhancedDescription: null,
      salesVelocity7d: null,
      salesVelocity30d: null,
      trendDirection: null,
      lastClassifiedAt: null,
    },
  },
  {
    id: 'refried-beans',
    title: 'Refried Beans',
    description: 'Creamy refried beans prepared in the traditional Mexican style.',
    image: '/images/menu/refried-beans.jpg',
    categories: ['sides'],
    pricing: panPricing(30, 50, 15, 20, 30, 35),
    tags: ['side', 'beans', 'popular', 'vegetarian', 'mexican'],
    menuEngineering: {
      classification: 'DOG',
      foodCost: 12,
      salesRank: 9,
      placementPriority: 9,
      visualWeight: 'medium',
      descriptionStrategy: 'maintain',
      badgeText: null,
      enhancedDescription: null,
      salesVelocity7d: null,
      salesVelocity30d: null,
      trendDirection: null,
      lastClassifiedAt: null,
    },
  },
  {
    id: 'topping-cheese',
    title: 'Cheese (per lb)',
    description: 'Shredded cheese, sold per pound. Perfect topping for tacos, fajitas, and more.',
    image: '/images/menu/cheese.jpg',
    categories: ['sides'],
    pricing: { type: 'per-each' as const, priceEach: 12 },
    tags: ['side', 'topping', 'mexican'],
    menuEngineering: {
      classification: 'DOG',
      foodCost: 28,
      salesRank: 21,
      placementPriority: 32,
      visualWeight: 'low',
      descriptionStrategy: 'minimize',
      badgeText: null,
      enhancedDescription: null,
      salesVelocity7d: null,
      salesVelocity30d: null,
      trendDirection: null,
      lastClassifiedAt: null,
    },
  },
  {
    id: 'topping-lettuce',
    title: 'Lettuce (small)',
    description: 'Shredded lettuce, small container. A fresh topping for any Mexican dish.',
    image: '/images/menu/lettuce.jpg',
    categories: ['sides'],
    pricing: { type: 'per-each' as const, priceEach: 12 },
    tags: ['side', 'topping', 'vegetarian', 'mexican'],
    menuEngineering: {
      classification: 'DOG',
      foodCost: 7,
      salesRank: 34,
      placementPriority: 33,
      visualWeight: 'low',
      descriptionStrategy: 'minimize',
      badgeText: null,
      enhancedDescription: null,
      salesVelocity7d: null,
      salesVelocity30d: null,
      trendDirection: null,
      lastClassifiedAt: null,
    },
  },
  {
    id: 'topping-tomato-slices',
    title: 'Tomato Slices (small)',
    description: 'Fresh tomato slices, small container.',
    image: '/images/menu/tomato-slices.jpg',
    categories: ['sides'],
    pricing: { type: 'per-each' as const, priceEach: 12 },
    tags: ['side', 'topping', 'vegetarian', 'mexican'],
    menuEngineering: {
      classification: 'DOG',
      foodCost: 10,
      salesRank: 35,
      placementPriority: 34,
      visualWeight: 'low',
      descriptionStrategy: 'minimize',
      badgeText: null,
      enhancedDescription: null,
      salesVelocity7d: null,
      salesVelocity30d: null,
      trendDirection: null,
      lastClassifiedAt: null,
    },
  },
  {
    id: 'topping-jalapeno-carrots',
    title: 'Jalapeño & Carrots (pint)',
    description: 'Pickled jalapeños and carrots, one pint. Adds a spicy kick to any dish.',
    image: '/images/menu/karolina-grabowska-yjvhactgjzs-unsplash.jpg',
    categories: ['sides'],
    pricing: { type: 'per-each' as const, priceEach: 9 },
    tags: ['side', 'topping', 'spicy', 'mexican'],
    menuEngineering: {
      classification: 'STAR',
      foodCost: 10,
      salesRank: 36,
      placementPriority: 35,
      visualWeight: 'low',
      descriptionStrategy: 'minimize',
      badgeText: null,
      enhancedDescription: null,
      salesVelocity7d: null,
      salesVelocity30d: null,
      trendDirection: null,
      lastClassifiedAt: null,
    },
  },
  {
    id: 'topping-pico-de-gallo',
    title: 'Pico de Gallo (pint)',
    description: 'Fresh pico de gallo made with diced tomatoes, onions, cilantro, and lime juice. One pint.',
    image: '/images/menu/pico-de-gallo.jpg',
    categories: ['sides'],
    pricing: { type: 'per-each' as const, priceEach: 9 },
    tags: ['side', 'topping', 'fresh', 'mexican'],
    menuEngineering: {
      classification: 'PLOWHORSE',
      foodCost: 12,
      salesRank: 19,
      placementPriority: 10,
      visualWeight: 'low',
      descriptionStrategy: 'maintain',
      badgeText: null,
      enhancedDescription: null,
      salesVelocity7d: null,
      salesVelocity30d: null,
      trendDirection: null,
      lastClassifiedAt: null,
    },
  },
  {
    id: 'topping-sour-cream',
    title: 'Sour Cream (16 oz)',
    description: 'Sour cream topping, 16 oz container. A cool complement to spicy dishes.',
    image: '/images/menu/sour-cream.jpg',
    categories: ['sides'],
    pricing: { type: 'per-each' as const, priceEach: 9 },
    tags: ['side', 'topping', 'mexican'],
    menuEngineering: {
      classification: 'DOG',
      foodCost: 12,
      salesRank: 20,
      placementPriority: 36,
      visualWeight: 'low',
      descriptionStrategy: 'minimize',
      badgeText: null,
      enhancedDescription: null,
      salesVelocity7d: null,
      salesVelocity30d: null,
      trendDirection: null,
      lastClassifiedAt: null,
    },
  },
  {
    id: 'topping-guacamole-chips',
    title: 'Guacamole w/ Chips (pint)',
    description: 'Fresh guacamole served with tortilla chips. One pint, serves 6-10 people.',
    image: '/images/menu/guacamole-chips.jpg',
    categories: ['sides'],
    pricing: { type: 'per-each' as const, priceEach: 9.75 },
    tags: ['side', 'topping', 'popular', 'mexican'],
    menuEngineering: {
      classification: 'STAR',
      foodCost: 24,
      salesRank: 13,
      placementPriority: 6,
      visualWeight: 'medium',
      descriptionStrategy: 'enhance',
      badgeText: 'Crowd Favorite',
      enhancedDescription: 'Fresh-made guacamole with crispy tortilla chips — our guests\' favorite appetizer add-on. Serves 6-10 people per pint.',
      salesVelocity7d: null,
      salesVelocity30d: null,
      trendDirection: null,
      lastClassifiedAt: null,
    },
  },
  {
    id: 'topping-house-salsa',
    title: 'House Salsa (liter)',
    description: 'Pepe\'s signature house salsa, one liter. A must-have for chips and more.',
    image: '/images/menu/house-salsa.jpg',
    categories: ['sides'],
    pricing: { type: 'per-each' as const, priceEach: 9.75 },
    tags: ['side', 'topping', 'popular', 'mexican'],
    menuEngineering: {
      classification: 'PUZZLE',
      foodCost: 10,
      salesRank: 14,
      placementPriority: 12,
      visualWeight: 'medium',
      descriptionStrategy: 'enhance',
      badgeText: 'House Favorite',
      enhancedDescription: 'Pepe\'s legendary house-made salsa by the liter — the perfect companion for chips, tacos, and everything on your table. A Chicago favorite since 1967.',
      salesVelocity7d: null,
      salesVelocity30d: null,
      trendDirection: null,
      lastClassifiedAt: null,
    },
  },
  {
    id: 'bunuelos',
    title: 'Buñuelos',
    description: 'Traditional Mexican fried dough dusted with cinnamon and sugar. Available in 30-piece or 60-piece trays.',
    image: '/images/menu/bunuelos.jpg',
    categories: ['sides'],
    pricing: panPricing(18, 35, 15, 20, 30, 40),
    tags: ['side', 'dessert', 'traditional', 'mexican'],
    menuEngineering: {
      classification: 'PUZZLE',
      foodCost: 8,
      salesRank: 28,
      placementPriority: 18,
      visualWeight: 'medium',
      descriptionStrategy: 'enhance',
      badgeText: 'Hidden Gem',
      enhancedDescription: 'Authentic Mexican buñuelos — light, crispy fried dough generously dusted with cinnamon sugar. A traditional dessert that brings the fiesta to any event.',
      salesVelocity7d: null,
      salesVelocity30d: null,
      trendDirection: null,
      lastClassifiedAt: null,
    },
  },
  {
    id: 'mini-churros',
    title: 'Mini Churros',
    description: 'Crispy mini churros available in Bavarian Cream, Strawberry, or Plain. 24 pieces per half pan, 48 pieces per full pan.',
    image: '/images/menu/mini-churros.jpg',
    categories: ['sides'],
    pricing: panPricing(25, 45, 12, 18, 24, 36),
    tags: ['side', 'dessert', 'popular', 'mexican'],
    menuEngineering: {
      classification: 'STAR',
      foodCost: 12,
      salesRank: 15,
      placementPriority: 6,
      visualWeight: 'high',
      descriptionStrategy: 'enhance',
      badgeText: 'Crowd Favorite',
      enhancedDescription: 'The perfect sweet finish — crispy golden mini churros filled with your choice of Bavarian Cream, Strawberry, or served Plain with cinnamon sugar. Always the first dessert to disappear at every event.',
      salesVelocity7d: null,
      salesVelocity30d: null,
      trendDirection: null,
      lastClassifiedAt: null,
    },
    variants: {
      label: 'Flavor',
      options: [
        { id: 'bavarian-cream', label: 'Bavarian Cream' },
        { id: 'strawberry', label: 'Strawberry' },
        { id: 'plain', label: 'Plain' },
      ],
      selectionMode: 'single',
    },
  },
];

// Get products by event type
export function getProductsByEventType(eventType: string | null): CateringProduct[] {
  if (!eventType) return CATERING_PRODUCTS;
  return CATERING_PRODUCTS.filter(product => product.categories.includes(eventType as any));
}

// Get product by ID
export function getProductById(id: string): CateringProduct | undefined {
  return CATERING_PRODUCTS.find(product => product.id === id);
}

// Get recommended products based on event type, budget, and what's already in the cart
export function getRecommendedProducts(
  eventType: string | null,
  cartItemIds: string[],
  budgetRange?: { min: number; max: number } | null,
  limit: number = 6,
): CateringProduct[] {
  let candidates = CATERING_PRODUCTS.filter(p => !cartItemIds.includes(p.id));

  if (eventType) {
    candidates = candidates.filter(p => p.categories.includes(eventType as any));
  }

  candidates = candidates.filter(p =>
    !p.tags?.includes('topping') &&
    !p.tags?.includes('chips')
  );

  candidates.sort((a, b) => {
    const aPopular = a.tags?.includes('popular') ? 1 : 0;
    const bPopular = b.tags?.includes('popular') ? 1 : 0;
    return bPopular - aPopular;
  });

  return candidates.slice(0, limit);
}

// Build a suggested menu for a given event type and headcount
export function getSuggestedMenu(
  eventType: string | null,
  headcount: number,
  budgetRange?: { min: number; max: number } | null,
): CateringProduct[] {
  const category = eventType || 'entrees';
  const available = CATERING_PRODUCTS.filter(p =>
    p.categories.includes(category as any) &&
    !p.tags?.includes('topping') &&
    !p.tags?.includes('chips')
  );

  const pick = (tags: string[], count: number): CateringProduct[] => {
    const matches = available.filter(p => tags.some(t => p.tags?.includes(t)));
    return matches.slice(0, count);
  };

  const menu: CateringProduct[] = [];

  if (category === 'appetizers') {
    menu.push(...pick(['appetizer', 'popular'], 2));
    menu.push(...pick(['salad'], 1));
  } else if (category === 'entrees') {
    menu.push(...pick(['fajita', 'popular'], 1));
    menu.push(...pick(['taco', 'popular'], 1));
    menu.push(...pick(['carnitas'], 1));
  } else if (category === 'sides') {
    menu.push(...pick(['rice'], 1));
    menu.push(...pick(['beans'], 1));
    menu.push(...pick(['dessert', 'popular'], 1));
  }

  const seen = new Set<string>();
  return menu.filter(p => {
    if (seen.has(p.id)) return false;
    seen.add(p.id);
    return true;
  });
}
